version: '3'

services:
  appv1:
    container_name: app_v1
    build: ./app_v1
    ports:
      - "5001:5000"
    networks:
      app_net:
        ipv4_address: 172.22.0.2

  appv2:
    container_name: app_v2
    build: ./app_v2
    ports:
    - "5002:5000"
    networks:
      app_net:
        ipv4_address: 172.22.0.3

  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    networks:
      app_net:
    depends_on:
    - appv1
    - appv2

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16